### ISSUE TITLE
Replace the custom query parser by a treetop parser

### ISSUE THREAD

**Issue by thekorn** [edelight/chef-solo-search#1]
chef-solo-search does parsing of lucene queries in its very own way, and because this way is limited it does not support the complete syntax of the query language.
As chef already ships a lucene grammar for treetop [0] it should be easy to reuse this grammar to run our queries.

[0] /usr/lib/ruby/vendor_ruby/chef/solr_query/lucene.treetop

**Comment by tobami** [comment]
That sounds like a great idea. Another important benefit of this move would be that the search would be Chef compliant, that is: search results would be guaranteed to be equal for both Chef Server and LittleChef users, which is kind of critical ;-)

**Comment by thekorn** [comment]
It's almost done in [0], besides escaped values every query which worked in the old version is working with the new one, and some more (e.g. grouping conditions is now possible).
Two kinds of quries are not yet implemented, and I'm not sure if we really want them: range queries and fuzzy matches.

[0] https://github.com/thekorn/chef-solo-search/tree/treetop-parser

**Comment by thekorn** [comment]
After reading some ruby docs, and understanding that 'a\:a' == "a\\:a" I fixed the test cases to work correctly with escaped values. Also "*" and "?" wildcards are working as described in the chef wiki.
So besides the missing range queries and fuzzy mathces I consider the treetop-parser branch [0] ready to be merged.

[0] https://github.com/thekorn/chef-solo-search/tree/treetop-parser
