### ISSUE TITLE
Treetop dependency removed from Chef in v11

### ISSUE THREAD

**Issue by benlangfeld** [edelight/chef-solo-search#17]
treetop was removed [here](https://github.com/opscode/chef/commit/862d971eed1c11e6990b1c08f00cac67a10a2e79)

treetop needs to be a dependency of this cookbook. PR coming soon.

**Comment by benlangfeld** [comment]
It seems to be impossible to install the gem before the library is loaded. Anyone have any ideas?

**Comment by benlangfeld** [comment]
Tagging @johntdyer

**Comment by benlangfeld** [comment]
```
benlangfeld: what about dealing with it in the default recipe? spox @ 20:01 
spox: The library is loaded before the recipe is compiled, so that's not possible. benlangfeld @ 20:01  
benlangfeld: possible if you're crafty spox @ 20:02 
spox: How? benlangfeld @ 20:02  
benlangfeld: i'll send a pull req later this afternoon spox @ 20:02
spox: Thanks!
```

**Comment by tobami** [comment]
Ah, great, looking forward to that :-)

**Comment by schisamo** [comment]
I opened https://github.com/edelight/chef-solo-search/pull/18 that covers ALL Chef 11 compat issues.
