### ISSUE TITLE
search no longer matches when running chef-solo

### ISSUE THREAD

**Issue by lkleen** [edelight/chef-solo-search#25]
given the following json

```
{
    "name": "memcache-01",
    "chef_environment": "_default",
    "run_list": [
        "role[memcache-server]"
    ],
    "automatic": {
        "hostname": "memcache-01",
        "ipaddress": "127.0.0.1",
        "cpu": { "total": "1" }
    },
    "normal": {
        "tags": [
            "pool-11211-libketama-01-consistent",
            "pool-11211-cids-01"
        ]
    }
}
```

when searching nodes the following expression will not match as expected:

   nodes = search(:node, "tags:*")

**Comment by tobami** [comment]
@tjwallace has answered to this question [in a comment](https://github.com/edelight/chef-solo-search/commit/c3a1461787b1abf546d145edc3dbc1e7cd55628c#commitcomment-2853796)

> make sure you include `"json_class": "Chef::Node"` in your node json files.
