### ISSUE TITLE
Failed search should return an empty list instead of nil

### ISSUE THREAD

**Issue by iartarisi** [edelight/chef-solo-search#32]
A failed chef client search returns a list with the first element being an empty list 

```
chef > Chef::Search::Query.new.search :node, "bogus"
 => [[], 0, 0]
```

AFAICS, the result of the same query using chef-solo and chef-solo-search is just an empty list i.e. `[]`

**Comment by thekorn** [comment]
Hi mapleoin, which version of chef are you using?

**Comment by iartarisi** [comment]
The first query above is from Chef 10.24.4. I updated the first comment to make it clear that I'm comparing Chef client output to Chef-solo + chef-solo-search output.

**Comment by michaelglass** [comment]
this is the current behavior: https://github.com/edelight/chef-solo-search/blob/master/tests/test_search.rb#L58
