### ISSUE TITLE
LoadError: cannot load such file -- search/overrides

### ISSUE THREAD

**Issue by Rodeoclash** [edelight/chef-solo-search#35]
I might be missing something obvious here (I'm follow instructions from http://blog.atwam.com/blog/2013/06/10/configuring-chef-solo-for-our-servers/)

Adding the cookbook (via Berksfile)

cookbook 'chef-solo-search'

Results in the error

LoadError: cannot load such file -- search/overrides

When I try to provision using vagrant. I've followed the instructions and the additional details in ticket 8 (including copying the search.rb and parser.rb files into a dummy cookbook) but it does not make any difference.

Any ideas?

**Comment by kylesloan** [comment]
Having the same issue https://gist.github.com/kylesloan/5880457

**Comment by tmatilai** [comment]
Unfortunately the cookbook on the community site is not usable due to a [Chef bug/restriction](http://tickets.opscode.com/browse/CHEF-672). You need to configure Berkshelf to download it from Github. So put to Berksfile something like:

``` ruby
cookbook 'chef-solo-search', github: 'edelight/chef-solo-search', ref: '0.4.0'
```

**Comment by Rodeoclash** [comment]
What a chore!

Still not having much luck:

Samuels-MacBook-Pro-2:api samuelrichardson (master) $ berks update chef-solo-search
...
Installing chef-solo-search (0.4.0) from github: 'edelight/chef-solo-search' with branch: 'master' over protocol: 'git'
...

Samuels-MacBook-Pro-2:api samuelrichardson (master) $ vagrant provision
....
[Berkshelf] Installing chef-solo-search (0.4.0) from git: 'git://github.com/edelight/chef-solo-search.git' with branch: 
....
Running chef-solo...
stdin: is not a tty
[2013-06-28T08:28:16+00:00] INFO: **\* Chef 10.12.0 ***
[2013-06-28T08:28:16+00:00] INFO: Setting the run_list to ["role[base]"] from JSON
[2013-06-28T08:28:16+00:00] INFO: Run List is [role[base]]
[2013-06-28T08:28:16+00:00] INFO: Run List expands to [apt, build-essential, git, users::sysadmins, sudo]
[2013-06-28T08:28:16+00:00] INFO: Starting Chef Run for vagrant-ubuntu-raring-64
[2013-06-28T08:28:16+00:00] INFO: Running start handlers
[2013-06-28T08:28:16+00:00] INFO: Start handlers complete.
[2013-06-28T08:28:17+00:00] ERROR: Running exception handlers
[2013-06-28T08:28:17+00:00] ERROR: Exception handlers complete
[2013-06-28T08:28:17+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-06-28T08:28:17+00:00] FATAL: LoadError: cannot load such file -- search/overrides
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by tmatilai** [comment]
@Rodeoclash that might be related to RiotGames/vagrant-berkshelf#17
Does it work if you reload or halt/up the VM?

Or maybe the broken 0.4.0 version was still cached. You can nuke it with `rm -r ~/.berkshelf/cookbooks/chef-solo-search-*`.

**Comment by Rodeoclash** [comment]
Good call on the cache, I blew that away and vagrant up/provision and everything worked fine. Still new to this so thanks for the help!

**Comment by micxer** [comment]
I have `cookbook 'chef-solo-search', github: 'edelight/chef-solo-search', tag: '0.4.0'` in my Berksfile and have removed the already downloaded cookbook but it always shows `Installing chef-solo-search (0.4.0) from site: 'http://cookbooks.opscode.com/api/v1/cookbooks'`.

I also upgraded my chef-client to `11.6.0`, Berkshelf is version `2.0.8`, Kitchen is at `1.0.0.beta.2`. Any idea what I am doing wrong?

**Comment by tmatilai** [comment]
Just a wild guess but maybe the Berksfile.lock has old reference? Anyway this seems more of a Berkshelf issue than chef-solo-search issue.

**Comment by micxer** [comment]
Thanks a lot. That was the one thing I overlooked!
