### ISSUE TITLE
partial search support

### ISSUE THREAD

**Issue by vtolstov** [edelight/chef-solo-search#36]
chef 11 have partial search support, does it possible to implement this in case of solo-search?

**Comment by TheSerapher** [comment]
:+1: I'd also like to see this feature.

**Comment by tobami** [comment]
It should certainly be possible.

For reference, Opscode's [blog post about partial search](http://www.opscode.com/blog/2012/10/31/introducing-partial-search-for-opscode-hosted-chef/)
