### ISSUE TITLE
Support access via symbols

### ISSUE THREAD

**Issue by e0da** [edelight/chef-solo-search#45]
You should be using a Mash or something that allows access via string index, symbol index, or dot notation. This is the behavior supported by search in Chef. I think the point of this is to work the same way, right?

Thanks!

**Comment by tobami** [comment]
Yes, you are right. There are cookbooks that fail because they use dot notation in the templates for variables that come from search results, so we always have to modify them to use single quotes.

**Comment by michaelglass** [comment]
@justinforce PR and you shall receive.  Keeping this open because it's required for feature parity.  However, I think with Chef Zero, this repo is gonna end not being heavily maintained.  Thoughts, @tobami ?

**Comment by michaelglass** [comment]
actually.  closing this as I think I like #42 more as a solution to it if we get around to it.

**Comment by e0da** [comment]
I would love to PR, but I left my job and I don't see much DevOps in my future. So long, Chef! We had a good run. I'm very grateful for all the time and test coverage that chef-solo-search netted me. Thanks!

**Comment by tobami** [comment]
@michaelglass sorry I missed your question. What Chef Zero will mean for this repo remain to be seen. I don't have any definitive thoughts yet. Are you planning to move to Chef Zero?

**Comment by michaelglass** [comment]
@tobami we've moved to Opsworks

**Comment by tobami** [comment]
@michaelglass cool to know, thanks for sharing. Is it working well for you?

**Comment by michaelglass** [comment]
Amazon has great tools but there are a few annoying inconsistencies.  alas & alck.
