### ISSUE TITLE
Exception when encrypted_data_bag_secret set but does not exist

### ISSUE THREAD

**Issue by seekely** [edelight/chef-solo-search#51]
Thanks for the very handy solo search!

Trying out the version of solo search in master and ran into the exception below (this does not happen in 0.5.1):

```
[2014-02-20T15:45:41-08:00] DEBUG: Re-raising exception: Errno::ENOENT - users_manage[sysadmin] (quid_base::users line 41) had an error: Errno::ENOENT: No such file or directory - file not found '/tmp/encrypted_data_bag_secret'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.0/lib/chef/encrypted_data_bag_item.rb:108:in `load_secret'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.0/lib/chef/encrypted_data_bag_item.rb:87:in `load'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search/overrides.rb:106:in `load_data_bag'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search/overrides.rb:128:in `block in search_data_bag'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search/overrides.rb:127:in `each'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search/overrides.rb:127:in `search_data_bag'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search/overrides.rb:53:in `search'
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/search/libraries/search.rb:69:in `search'
```

When the support for encrypted data bags was added (#38), looks like the way data bags load changed a bit.  The exception above kicks up when  encrypted_data_bag_secret is set, but the file does not exist.  Our encrypted_data_bag_secret has been defaulted to /tmp/encrypted_data_bag_secret even though we currently do not use encrypted data bags, so we hit the exception and the Chef run stops.

**Comment by michaelglass** [comment]
do you know how chef server handles this?  Not sure if we should raise an exception or not.

**Comment by seekely** [comment]
I'll find out and let you know.  I'll also find out where/why encrypted_data_bag_secret  is being set by default.

**Comment by michaelglass** [comment]
thanks

**Comment by tmatilai** [comment]
In this case it's configured by Vagrant, see mitchellh/vagrant#2984. It will be fixed in Vagrant 1.5.

But maybe the existence of the file should anyway be checked [in this if](https://github.com/edelight/chef-solo-search/blob/848e98f/libraries/search/overrides.rb#L104) too? I understand [this comment](https://github.com/opscode/chef/blob/11.10.4/lib/chef/config.rb#L396-L407) so that Chef 12 will unconditionally set the default.

**Comment by michaelglass** [comment]
should be fixed in master.  Thanks @tmatilai, @seekely, and @tobami

**Comment by tobami** [comment]
@michaelglass  Thanks to you!
