### ISSUE TITLE
With Subdirectories in Libraries knife cookbook upload fails

### ISSUE THREAD

**Issue by duallain** [edelight/chef-solo-search#54]
The bug is due to this ticket: https://tickets.opscode.com/browse/CHEF-672
Sub-directories of the library folder aren't dealt with correctly.   

Is it possible to flatten the directory structure of 'libraries'? 

I also noticed there was a little discussion of the issue here: https://github.com/edelight/chef-solo-search/issues/30

here is the pull request: https://github.com/edelight/chef-solo-search/pull/55

**Comment by michaelglass** [comment]
merged with a slight change to the tests and some history cleanup.  See changes here: https://github.com/edelight/chef-solo-search/commit/3791086403eb677528b788529c8fb169ce73b892
