### ISSUE TITLE
Treetop 1.5.0 breaks search query parser

### ISSUE THREAD

**Issue by budnik** [edelight/chef-solo-search#57]
Treetop just updated to `1.5.0` and breaks `LuceneParser` e.g.:

```
# treetop 1.4.1:
Query.parse('foo:bar AND baz:quaz')
=> Body offset=0, "foo:bar AND baz:quaz":
  BinaryOp+BinaryOp0 offset=0, "foo:bar AND baz:quaz" (boolean_operator,body):
    Field+Field0 offset=0, "foo:bar" (field_name):
      FieldName+FieldName0 offset=0, "foo"
      Term+Term1 offset=4, "bar" (valid_letter)
    AndOperator offset=8, "AND"
    Body offset=12, "baz:quaz":
      Field+Field0 offset=12, "baz:quaz" (field_name):
        FieldName+FieldName0 offset=12, "baz"
        Term+Term1 offset=16, "quaz" (valid_letter)
```

```
# treetop 1.5.0:
Query.parse('foo:bar AND baz:quaz')
=> Body offset=0, "foo:bar AND baz:quaz":
  Field+Field0 offset=0, "foo:bar" (field_name):
    FieldName+FieldName0 offset=0, "foo"
    Term+Term1 offset=4, "bar" (valid_letter)
  Term+Term1 offset=8, "AND" (valid_letter)
  Field+Field0 offset=12, "baz:quaz" (field_name):
    FieldName+FieldName0 offset=12, "baz"
    Term+Term1 offset=16, "quaz" (valid_letter)
```

**Comment by cjheath** [comment]
This was a defect in the case-insensitive matching in Treetop 1.5.0 - fixed just now in 1.5.1. Thanks for the report, please re-test with 1.5.1.

**Comment by mi-wood** [comment]
Would it be wise to fix the treetop gem install to a known stable version with solo-search? 1.5.0 broke some cookbook dependencies (such as the users cookbook) that use AND queries. Happy to put in the PR.

**Comment by michaelglass** [comment]
please.  http://www.ruby-doc.org/stdlib-1.9.3/libdoc/rubygems/rdoc/Kernel.html#method-i-gem

**Comment by cjheath** [comment]
I yanked the broken 1.5.0 Treetop version, which was only online for 24 hours anyway. You shouldn't need to take any further action.

**Comment by mi-wood** [comment]
I'm going to set my repo to 1.5.1, so it doesn't break chef deployments with future builds (like it did yesterday). I'm testing my changes atm. Will probably change this in the future with bugs or any security patches. This seems like a best practice for the way we're using solo-search (although you seem to be on top of treetop bug fixes @cjheath . thanks! ). I can still put in a PR if people want the main repo to use this.

**Comment by cjheath** [comment]
1.5.2 is already in Github. I'm pretty sure you don't want to lock the main repo to 1.5.1

**Comment by michaelglass** [comment]
@cjheath the point is we'll bring in new versions as needed / with testing.
